/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.Person;
import model.PersonDirectory;

/**
 *
 * @author rohanjauhari
 */
public class ViewSearchJPanel extends javax.swing.JPanel {
    PersonDirectory personDirectory;
    JPanel detailsJPanel;
    Person foundPerson;
    /**
     * Creates new form ViewSearchJPanel
     */
    public ViewSearchJPanel(JPanel container, Person p, boolean updateFlag) {
        detailsJPanel = container;
        foundPerson = p;
        initComponents();
        txtAge.setText(Byte.toString(foundPerson.getAge()));
        txtCityH.setText(foundPerson.homeAddress.getCity());
        txtCityW.setText ( foundPerson.workAddress.getCity());
        txtFirstName.setText(foundPerson.getFirstName());
        txtLastName.setText(foundPerson.getLastName());
        txtPhoneH.setText ( Long.toString(foundPerson.homeAddress.getPhone()));
        txtPhoneW.setText ( Long.toString(foundPerson.workAddress.getPhone()));
        txtSsn.setText( foundPerson.getSsn());
        txtStateH.setText(foundPerson.homeAddress.getState());
        txtStateW.setText ( foundPerson.workAddress.getState());
        txtStreetH.setText ( foundPerson.homeAddress.getStreet());
        txtStreetW.setText( foundPerson.workAddress.getStreet());
        txtUnitH.setText( Integer.toString(foundPerson.homeAddress.getUnit()));
        txtUnitW.setText( Integer.toString(foundPerson.workAddress.getUnit()));
        txtZipH.setText( Integer.toString(foundPerson.homeAddress.getZip()));
        txtZipW.setText ( Integer.toString(foundPerson.workAddress.getZip()));
        
        
        if (!updateFlag){
            txtAge.setEditable(false);
            txtCityH.setEditable(false);
            txtCityW.setEditable(false);
            txtFirstName.setEditable(false);
            txtLastName.setEditable(false);
            txtPhoneH.setEditable(false);
            txtPhoneW.setEditable(false);
            txtSsn.setEditable(false);
            txtStateH.setEditable(false);
            txtStateW.setEditable(false);
            txtStreetH.setEditable(false);
            txtStreetW.setEditable(false);
            txtUnitH.setEditable(false);
            txtUnitW.setEditable(false);
            txtZipH.setEditable(false);
            txtZipW.setEditable(false);
            btnSave.setEnabled (false);
            btnUpdate. setEnabled (true);
        }
        else{
            btnSave.setEnabled (true);
            btnUpdate. setEnabled (false);
            txtAge.setEditable(true);
        txtCityH.setEditable(true);
        txtCityW.setEditable(true);
        txtFirstName.setEditable(true);
        txtLastName.setEditable(true);
        txtPhoneH.setEditable(true);
        txtPhoneW.setEditable(true);
        txtSsn.setEditable(true);
        txtStateH.setEditable(true);
        txtStateW.setEditable(true);
        txtStreetH.setEditable(true);
        txtStreetW.setEditable(true);
        txtUnitH.setEditable(true);
        txtUnitW.setEditable(true);
        txtZipH.setEditable(true);
        txtZipW.setEditable(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtSsn = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        txtStreetH = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtUnitH = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtStateH = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtCityH = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtPhoneH = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtStreetW = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        txtUnitW = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtStateW = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtCityW = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPhoneW = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtZipW = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        txtZipH = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("First Name");

        txtFirstName.setEditable(false);
        txtFirstName.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel2.setText("Last Name");

        txtLastName.setEditable(false);
        txtLastName.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel3.setText("Age");

        txtAge.setEditable(false);
        txtAge.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel4.setText("Social Security Number");

        txtSsn.setEditable(false);
        txtSsn.setPreferredSize(new java.awt.Dimension(100, 23));

        btnBack.setText("<<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        txtStreetH.setEditable(false);
        txtStreetH.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel5.setText("Home unit");

        txtUnitH.setEditable(false);
        txtUnitH.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel6.setText("Home state");

        txtStateH.setEditable(false);
        txtStateH.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel7.setText("Home city");

        txtCityH.setEditable(false);
        txtCityH.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel8.setText("Home Street");

        txtPhoneH.setEditable(false);
        txtPhoneH.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel9.setText("Work Street");

        txtStreetW.setEditable(false);
        txtStreetW.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel10.setText("Work unit");

        txtUnitW.setEditable(false);
        txtUnitW.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel11.setText("Work state");

        txtStateW.setEditable(false);
        txtStateW.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel12.setText("Home phone");

        jLabel13.setText("Work city");

        txtCityW.setEditable(false);
        txtCityW.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel14.setText("Work phone");

        txtPhoneW.setEditable(false);
        txtPhoneW.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel15.setText("Work zip");

        txtZipW.setEditable(false);
        txtZipW.setPreferredSize(new java.awt.Dimension(100, 23));

        jLabel16.setText("Home zip");

        txtZipH.setEditable(false);
        txtZipH.setPreferredSize(new java.awt.Dimension(100, 23));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnBack)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(136, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnSave)
                                .addGap(153, 153, 153)
                                .addComponent(btnUpdate))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(115, 115, 115)
                                .addComponent(txtUnitW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtPhoneH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtStreetW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addGap(115, 115, 115)
                                        .addComponent(txtPhoneW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addGap(115, 115, 115)
                                        .addComponent(txtCityW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(115, 115, 115)
                                        .addComponent(txtZipW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(115, 115, 115)
                                    .addComponent(txtStateW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(115, 115, 115)
                                .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(115, 115, 115)
                                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(115, 115, 115)
                                .addComponent(txtStateH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(115, 115, 115)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtStreetH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtUnitH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel16)
                                    .addGap(115, 115, 115)
                                    .addComponent(txtZipH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel7))
                            .addComponent(txtCityH, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(183, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnBack)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtSsn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtStreetH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUnitH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtStateH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtCityH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtZipH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPhoneH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtStreetW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtUnitW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtStateW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtCityW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtPhoneW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtZipW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnUpdate))
                .addContainerGap(75, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        detailsJPanel.remove(this);
        CardLayout layout = (CardLayout) detailsJPanel.getLayout();
        layout. previous (detailsJPanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        txtAge.setEditable(true);
        txtCityH.setEditable(true);
        txtCityW.setEditable(true);
        txtFirstName.setEditable(true);
        txtLastName.setEditable(true);
        txtPhoneH.setEditable(true);
        txtPhoneW.setEditable(true);
        txtSsn.setEditable(true);
        txtStateH.setEditable(true);
        txtStateW.setEditable(true);
        txtStreetH.setEditable(true);
        txtStreetW.setEditable(true);
        txtUnitH.setEditable(true);
        txtUnitW.setEditable(true);
        txtZipH.setEditable(true);
        txtZipW.setEditable(true);
        btnSave.setEnabled (true);
        btnUpdate.setEnabled (false);
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        if (txtAge.getText().isBlank() || txtCityH.getText().isBlank() || txtCityW.getText().isBlank() || txtFirstName.getText().isBlank() || txtLastName.getText().isBlank() || txtPhoneH.getText().isBlank() || txtPhoneW.getText().isBlank() || txtSsn.getText().isBlank() || txtStateH.getText().isBlank() || txtStateW.getText().isBlank() || txtStreetH.getText().isBlank() || txtStreetW.getText().isBlank() || txtUnitH.getText().isBlank() || txtUnitW.getText().isBlank() || txtZipH.getText().isBlank() || txtZipW.getText().isBlank()){
            JOptionPane.showMessageDialog (null, "All fields are mandatory.");
            return;
        }
        
        try{
                Integer.parseInt(txtAge.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Age is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
                return;
            }
            
            try{
                Integer.parseInt(txtSsn.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "SSN is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
                return;
            }
            
            try{
                Integer.parseInt(txtZipH.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Home zip is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Integer.parseInt(txtZipW.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Work zip is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Long.parseLong(txtPhoneH.getText());
            
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Home Phone is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Long.parseLong(txtPhoneW.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Work Phone is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Integer.parseInt(txtUnitH.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Home unit is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
            try{
                Integer.parseInt(txtUnitW.getText());
            }
            catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Work unit is not a number", "Warning", JOptionPane.WARNING_MESSAGE) ;
            return;
            }
            
//        Person person = personDirectory.addNewPerson();
        foundPerson.setFirstName(txtFirstName.getText());
        foundPerson.setAge(txtAge.getText().getBytes()[0]);
        foundPerson.setLastName(txtLastName.getText());
        foundPerson.setSsn(txtSsn.getText());
        foundPerson.setHomeAddress(txtStreetH.getText(),txtStateH.getText(),Integer.valueOf(txtZipH.getText()),txtCityH.getText(),Integer.valueOf(txtUnitH.getText()),Long.valueOf(txtPhoneH.getText()));
        foundPerson.setWorkAddress(txtStreetW.getText(),txtStateW.getText(),Integer.valueOf(txtZipW.getText()),txtCityW.getText(),Integer.valueOf(txtUnitW.getText()),Long.valueOf(txtPhoneW.getText()));
        
        
        JOptionPane.showMessageDialog(null, "Account successfully updated.", "Success", JOptionPane.INFORMATION_MESSAGE);
        
        txtAge.setEditable(false);
        txtCityH.setEditable(false);
        txtCityW.setEditable(false);
        txtFirstName.setEditable(false);
        txtLastName.setEditable(false);
        txtPhoneH.setEditable(false);
        txtPhoneW.setEditable(false);
        txtSsn.setEditable(false);
        txtStateH.setEditable(false);
        txtStateW.setEditable(false);
        txtStreetH.setEditable(false);
        txtStreetW.setEditable(false);
        txtUnitH.setEditable(false);
        txtUnitW.setEditable(false);
        txtZipH.setEditable(false);
        txtZipW.setEditable(false);
        
        btnSave.setEnabled (false);
        btnUpdate. setEnabled (true);
        
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtCityH;
    private javax.swing.JTextField txtCityW;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneH;
    private javax.swing.JTextField txtPhoneW;
    private javax.swing.JTextField txtSsn;
    private javax.swing.JTextField txtStateH;
    private javax.swing.JTextField txtStateW;
    private javax.swing.JTextField txtStreetH;
    private javax.swing.JTextField txtStreetW;
    private javax.swing.JTextField txtUnitH;
    private javax.swing.JTextField txtUnitW;
    private javax.swing.JTextField txtZipH;
    private javax.swing.JTextField txtZipW;
    // End of variables declaration//GEN-END:variables
}
